kakao:
    api:
        key: ${KAKAO_API_KEY}
    karlo:
        image_generate_url: ${KARLO_API_URL}
        generate_image:
            negative_prompt: ${NEGATIVE_PROMPT}
            style:
                default: ${KARLO_DEFAULT_STYLE}