spring:
    profiles:
        active: ${profile}
        include: oauth, aws, openai, actuator, r2, kakao

firestore:
    emulator-host: ${FIRESTORE_EMULATOR_HOST:#{null}}
    project-id: ${FIRESTORE_PROJECT_ID:draw-my-today}
    database-id: ${FIRESTORE_DATABASE_ID:(default)}

encryptor:
    secret:
        key: ${ENCRYPTOR_SECRET_KEY}
presigned-image:
    expiration:
        admin-diaries: ${PRESIGNED_IMAGE_EXPIRATION_ADMIN_DIARIES}

stability:
    api:
        key: ${STABILITY_API_KEY}
    stable_image_core:
        url: https://api.stability.ai/v1/generation/stable-diffusion-xl-1024-v1-0/text-to-image
        negative_prompt: ${NEGATIVE_PROMPT}



---
spring.config.activate.on-profile: local

spring:
    jackson:
        serialization:
            write-dates-as-timestamps: false

logging:
    level:
        tipitapi.drawmytoday: DEBUG
        com.google.cloud.firestore: WARN
        com.google.firebase: WARN
---
spring.config.activate.on-profile: develop

---
spring.config.activate.on-profile: prod1
server.port: 8081

---
spring.config.activate.on-profile: prod2
server.port: 8082